name: Update News

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"
concurrency:
  group: update-news
  cancel-in-progress: true

jobs:
  update-news:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Dependencies
        run: npm ci

      - name: Generate News JSON
        run: node scripts/fetchNews.js

      - name: Commit JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add -A output

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto update news"
            git pull --rebase origin main

            git push origin main
          fi
